# Generated by Django 5.1.2 on 2025-11-16 13:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration", models.FloatField(help_text="Длительность в секундах")),
                (
                    "storage_path",
                    models.CharField(help_text="Путь к файлу в MinIO", max_length=500),
                ),
                (
                    "file_size",
                    models.BigIntegerField(help_text="Размер файла в байтах"),
                ),
                ("fps", models.FloatField(help_text="Кадры в секунду")),
                (
                    "resolution",
                    models.CharField(
                        help_text="Разрешение (например, 1920x1080)", max_length=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_files",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "db_table": "videos_video_files",
            },
        ),
        migrations.CreateModel(
            name="Clip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_offset",
                    models.FloatField(
                        help_text="Начало клипа в секундах от начала видео"
                    ),
                ),
                (
                    "end_offset",
                    models.FloatField(
                        help_text="Конец клипа в секундах от начала видео"
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=255)),
                ("download_url", models.URLField(blank=True, max_length=500)),
                ("is_annotated", models.BooleanField(default=False)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="clip_thumbnails/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "video_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clips",
                        to="videos.videofile",
                    ),
                ),
            ],
            options={
                "db_table": "videos_clips",
            },
        ),
        migrations.CreateModel(
            name="VideoAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                (
                    "start_time",
                    models.FloatField(
                        help_text="Время начала в секундах от начала клипа"
                    ),
                ),
                (
                    "end_time",
                    models.FloatField(
                        help_text="Время окончания в секундах от начала клипа"
                    ),
                ),
                (
                    "bbox",
                    models.JSONField(
                        help_text="Координаты bounding box в формате {'x': 0, 'y': 0, 'w': 0, 'h': 0}"
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="videos.clip",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos_video_annotations_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "videos_video_annotations",
                "indexes": [
                    models.Index(
                        fields=["clip", "label"], name="vid_annot_clip_label_idx"
                    ),
                    models.Index(fields=["status"], name="videos_vid_annot_status_idx"),
                    models.Index(
                        fields=["created_at"], name="vid_annot_created_at_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="videofile",
            index=models.Index(
                fields=["camera", "start_time"], name="vid_files_cam_start_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videofile",
            index=models.Index(fields=["created_at"], name="vid_files_created_at_idx"),
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(
                fields=["video_file", "start_offset"],
                name="vid_clips_vf_start_offset_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(
                fields=["is_annotated"], name="videos_clips_is_annotated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clip",
            index=models.Index(fields=["created_at"], name="vid_clips_created_at_idx"),
        ),
    ]
