# Generated by Django 5.1.2 on 2025-11-16 13:14

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cameras", "0001_initial"),
        ("videos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("line_crossing", "Line Crossing"),
                            ("zone_violation", "Zone Violation"),
                            ("behavior_detection", "Behavior Detection"),
                            ("loitering", "Loitering"),
                            ("object_left_behind", "Object Left Behind"),
                            ("speed_detection", "Speed Detection"),
                            ("counting", "Counting"),
                            ("custom", "Custom Rule"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "conditions",
                    models.JSONField(
                        default=dict, help_text="Условия срабатывания правила"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_rules",
                        to="cameras.camera",
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_rules",
                        to="cameras.line",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_rules",
                        to="cameras.zone",
                    ),
                ),
            ],
            options={
                "db_table": "events_rules",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                (
                    "object_class",
                    models.CharField(
                        help_text="Класс обнаруженного объекта", max_length=100
                    ),
                ),
                (
                    "track_id",
                    models.CharField(help_text="ID трека объекта", max_length=100),
                ),
                ("bbox", models.JSONField(help_text="Координаты bounding box")),
                (
                    "confidence",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_events",
                        to="cameras.camera",
                    ),
                ),
                (
                    "clip",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_events",
                        to="videos.clip",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events_events_resolved_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_events",
                        to="events.rule",
                    ),
                ),
            ],
            options={
                "db_table": "events_events",
            },
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["camera", "rule_type"], name="events_rules_cam_rule_type_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["severity", "enabled"], name="ev_rules_severity_enabled_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["created_at"], name="events_rules_created_at_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["camera", "timestamp"], name="ev_events_cam_timestamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["rule", "severity"], name="ev_events_rule_severity_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["resolved", "timestamp"], name="ev_events_res_tstamp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["bbox"], name="events_events_bbox_gin"
            ),
        ),
    ]
