# Generated by Django 5.1.2 on 2025-11-16 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("email", "Email"),
                            ("webhook", "Webhook"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        help_text="Конфигурация канала (токены, адреса и т.д.)"
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                (
                    "schedule",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Расписание отправки уведомлений",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "alerts_alert_channels",
                "indexes": [
                    models.Index(
                        fields=["channel_type", "enabled"],
                        name="alert_chann_type_enabled_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField()),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="events.event",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="alerts.alertchannel",
                    ),
                ),
            ],
            options={
                "db_table": "alerts_alerts",
                "indexes": [
                    models.Index(
                        fields=["event", "status"], name="alert_event_status_idx"
                    ),
                    models.Index(
                        fields=["channel", "status"], name="alert_channel_status_idx"
                    ),
                    models.Index(fields=["created_at"], name="alert_created_at_idx"),
                ],
            },
        ),
    ]
