# Generated by Django 5.1.2 on 2025-11-16 13:14

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("rtsp_url", models.URLField(max_length=500)),
                ("location", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "snapshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="camera_snapshots/"
                    ),
                ),
                ("vendor", models.CharField(blank=True, max_length=100)),
                ("stream_settings", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "cameras_cameras",
                "indexes": [
                    models.Index(fields=["status"], name="cameras_cameras_status_idx"),
                    models.Index(
                        fields=["created_at"], name="cameras_cameras_created_at_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "points",
                    models.JSONField(
                        help_text="Координаты линии в формате [{'x': 0, 'y': 0}, {'x': 1, 'y': 1}]"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("horizontal", "Horizontal"),
                            ("vertical", "Vertical"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                (
                    "allowed_objects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "forbidden_objects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "db_table": "cameras_lines",
                "indexes": [
                    models.Index(
                        fields=["camera", "direction"],
                        name="cam_lines_cam_direction_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="cameras_lines_is_active_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "polygon",
                    models.JSONField(
                        help_text="Координаты полигона в формате [{'x': 0, 'y': 0}, ...]"
                    ),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Zone"),
                            ("exit", "Exit Zone"),
                            ("restricted", "Restricted Area"),
                            ("counting", "Counting Zone"),
                            ("detection", "Detection Zone"),
                            ("custom", "Custom Zone"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "allowed_objects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Разрешенные типы объектов (person, car, truck, etc.)",
                        size=None,
                    ),
                ),
                (
                    "forbidden_objects",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        help_text="Запрещенные типы объектов",
                        size=None,
                    ),
                ),
                (
                    "max_objects",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Максимальное количество объектов в зоне (0 = без ограничений)",
                    ),
                ),
                (
                    "min_duration",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Минимальная продолжительность пребывания в зоне (секунды)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zones",
                        to="cameras.camera",
                    ),
                ),
            ],
            options={
                "db_table": "cameras_zones",
                "indexes": [
                    models.Index(
                        fields=["camera", "zone_type"],
                        name="cam_zones_cam_zone_type_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="cameras_zones_is_active_idx"
                    ),
                ],
            },
        ),
    ]
