# Generated by Django 5.1.2 on 2025-11-16 13:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("model_file", models.FileField(upload_to="ml_models/")),
                ("training_dataset_size", models.PositiveIntegerField(default=0)),
                (
                    "accuracy",
                    models.FloatField(
                        help_text="Точность модели от 0 до 1",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.CharField(default="1.0.0", max_length=50)),
            ],
            options={
                "db_table": "ml_models",
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="ml_models_name_75d659_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="ml_models_created_d43da9_idx"
                    ),
                ],
            },
        ),
    ]
